### ISSUE TITLE
About user_graph_dict_file

### ISSUE THREAD

**Issue by THU-Yu-Shang** [enoche/MMRec#1]
Hi, I meet some problems when running the codes caused by missing the file "user_graph_dict_file.npy", I wonder how to get this file, thank you!

**Comment by THU-Yu-Shang** [comment]
when running DualGNN

**Comment by enoche** [comment]
> when running DualGNN

Great to know you are running the framework. 
DualGNN requires additional preprocessing to generate the u-u graph.
I just upload the python script in `preprocessing` [dir](https://github.com/enoche/MMRec/tree/master/preprocessing) and update `README` for your reference.

Please kindly post any problems when running the code. Thanks.

**Comment by THU-Yu-Shang** [comment]
Got it! Thanks for the timely reply!

**Comment by enoche** [comment]
> Got it! Thanks for the timely reply!

You are welcome. BTW, all scripts for raw data preprocessing are also updated for your reference.
