### ISSUE TITLE
why `calculate_loss` of ItemKNNCBF is return `torch.tensor(0.0)`

### ISSUE THREAD

**Issue by zhongshsh** [enoche/MMRec#11]
https://github.com/enoche/MMRec/blob/master/src/models/itemknncbf.py#L67-L69

```
    def calculate_loss(self, interaction):
        tmp_v = torch.tensor(0.0)
        return tmp_v
```

ItemKNNCBF | [Are We Really Making Much Progress? A Worrying Analysis of Recent Neural Recommendation Approaches](https://arxiv.org/pdf/1907.06902.pdf)
-- | --

**Comment by enoche** [comment]
Thanks for your feedback. 
`calculate_loss` is a dummy function.
ItemKNNCBF has no parameters to learn. Please check the paper.
