### ISSUE TITLE
Lack of the necessary script tools/generate-u-u-matrix.py for running DRAGON

### ISSUE THREAD

**Issue by WeixinChen98** [enoche/MMRec#12]
Hi, could you please upload the script mentioned in dragon.py?

```
# user-graph need to be generated by the following script
# tools/generate-u-u-matrix.py
self.user_graph_dict = np.load(os.path.join(dataset_path, config['user_graph_dict_file']), allow_pickle=True).item()
```

Thanks!

**Comment by enoche** [comment]
Hi, @WeixinChen98  Thanks for your feedback.
THe u-u graph is generated in the way by: https://github.com/enoche/MMRec/blob/master/preprocessing/dualgnn-gen-u-u-matrix.py

**Comment by WeixinChen98** [comment]
Thanks for your explanation! @enoche
