### ISSUE TITLE
ModuleNotFoundError: No module named 'common.encoders', LightGCN_Encoder

### ISSUE THREAD

**Issue by zhongshsh** [enoche/MMRec#13]
when I try to run `SELFCFED_LGN`, i.e. SelfCF (?). the code raises an error whose message is as follows:

```
    from common.encoders import LightGCN_Encoder
ModuleNotFoundError: No module named 'common.encoders'
```

It means that `LightGCN_Encoder` is not existed.

**Comment by tjehddn560** [comment]
Maybe you install 'common' package through pip. So, if you change 'common' folder's name to something else(eg.common1) and modify your code like 'from common1.encoders ~...', then your code will run well.

**Comment by zhongshsh** [comment]
Thank you for your reply. but I can't find the module `LightGCN_Encoder` in this repo
![image](https://github.com/enoche/MMRec/assets/62104945/9ad0637f-78d4-4f77-84ba-b366706da35c)

**Comment by enoche** [comment]
@zhongshsh 
Thank you so much for your feedback. We have resolved the issue by adding the missing **encoders.py** file and updating **selfcfed_lgn.py** to correctly reference it. We appreciate your help in identifying and fixing this bug. 😊

@tjehddn560 Thanks a lot for your kind assistance on this issue.
