### ISSUE TITLE
Rely on this framework to add CF models.

### ISSUE THREAD

**Issue by RSnewbie** [enoche/MMRec#17]
Thank you very much for your excellent work.

Now I would like to rely on your framework to implement a couple of CF-based recommendation models, could you please tell me if there is any guideline to add the models?

Sincerely.

**Comment by enoche** [comment]
Hi, @RSnewbie  Thanks for your feedback. We are busy finalizing the detailed documents about this framework.

You may refer this dir: https://github.com/enoche/MMRec/tree/master/src/models, to learn how models are implemented. 

1. Inherit Class: `GeneralRecommender`
2. Init your model in `__init__`
3. Implement your CF model in `calculate_loss` 
4. Predict recommendation result in `full_sort_predict`

**Comment by RSnewbie** [comment]
> Hi, @RSnewbie Thanks for your feedback. We are busy finalizing the detailed documents about this framework.
> 
> You may refer this dir: https://github.com/enoche/MMRec/tree/master/src/models, to learn how models are implemented.
> 
> 1. Inherit Class: `GeneralRecommender`
> 2. Init your model in `__init__`
> 3. Implement your CF model in `calculate_loss`
> 4. Predict recommendation result in `full_sort_predict`

Thank you for your response.

Reproducing it as per your guide is ok, but what confuses me is the hyperparameter tuning part, I found that both overall.yaml and model.yaml involve hyperparameter names. If I don't want to do hyperparameter exploration, how can I set it up?

Sincerely.

**Comment by RSnewbie** [comment]
> Hi, @RSnewbie Thanks for your feedback. We are busy finalizing the detailed documents about this framework.
> 
> You may refer this dir: https://github.com/enoche/MMRec/tree/master/src/models, to learn how models are implemented.
> 
> 1. Inherit Class: `GeneralRecommender`
> 2. Init your model in `__init__`
> 3. Implement your CF model in `calculate_loss`
> 4. Predict recommendation result in `full_sort_predict`

Thank you for your response.

Reproducing it as per your guide is ok, but what confuses me is the hyperparameter tuning part, I found that both overall.yaml and model.yaml involve hyperparameter names. If I don't want to do hyperparameter exploration, how can I set it up?

Sincerely.
