### ISSUE TITLE
What was the first work that used not only text but images for recommendations?

### ISSUE THREAD

**Issue by angelayang666b4** [enoche/MMRec#2]
Hi, I am working on multimodal recommendations now. I am a little bit confused about what is the first work that used not only text but images for review-based recommender systems? I saw many works just use reviews but not images.

**Comment by enoche** [comment]
Hi, angelayang666b4, thanks for asking. As far as I know not many works have been conducted in that domain. However, one possible approach may be to project images and reviews into the same space for recommendation.

**Comment by enoche** [comment]
"Personalized Fashion Recommendation with Visual Explanations based on Multimodal Attention Network" counts one, published on SIGIR'19.

**Comment by angelayang666b4** [comment]
Thank you for your reply :)

**Comment by enoche** [comment]
You are always welcomed.  Thanks.
I'll close this issue if no further questions.
