### ISSUE TITLE
Some problem about layergcn

### ISSUE THREAD

**Issue by wenyu1009** [enoche/MMRec#21]
When I run layergcn，
https://github.com/enoche/MMRec/blob/58cbd75f0e7a333e91fd12c51538a4d13ed678c2/src/models/layergcn.py#L56-L61

When we train the model using GPU, and enter line 58. An error will be reported. 
The parameters are not on the same device, one GPU and one CPU.
When we remove .to(self.device), the problem is solved.

**Comment by enoche** [comment]
Thanks for your feedback.
Yes. removing .to(self.device) in random setting is correct, will update soon~
