### ISSUE TITLE
About user_graph_dict_file

### ISSUE THREAD

**Issue by heejkoo1** [enoche/MMRec#23]
Dear @enoche,

Thank you for updating this repo. Actually, I am encountering some difficulties with preprocessing user_graph_dict_file. Do you mind sharing it via google drive?

Best,
heejkoo

**Comment by enoche** [comment]
@heejkoo1 Here is the [user_graph_dict for baby dataset](https://drive.google.com/file/d/1e1BYjeBmJqhwduOjdTfBbJLZpKiHdm7A/view?usp=sharing)

As my drive storage will run out, I skip other datasets. I would encourage to generate via preprocessing scripts.

**Comment by heejkoo1** [comment]
Thank you for sharing the data. I will make attempts to follow the scripts.

Best,
heejkoo
