### ISSUE TITLE
Amazon product data

### ISSUE THREAD

**Issue by Panamera2333** [enoche/MMRec#25]
Hello author, I would like to know how the image_featuresSportsAnd-Outdoors.b file for the extracted image feature in the preprocessing section of the dataset, 3feature encoder ipynb, was obtained. Do you have any code to extract image features and save them as. b files

**Comment by enoche** [comment]
Hi, @Panamera2333 Thank you for expressing interest in our repository.


The file `image_features_Sports_and_Outdoors.b` is a raw dataset that can be obtained from the Amazon Product Dataset. For instructions on how to download this dataset, please refer to the [relevant issue](https://github.com/enoche/BM3/issues/9#issuecomment-1843973175) in our another repository.

**Comment by Panamera2333** [comment]
> Hi, @Panamera2333 Thank you for expressing interest in our repository.
> 
> The file `image_features_Sports_and_Outdoors.b` is a raw dataset that can be obtained from the Amazon Product Dataset. For instructions on how to download this dataset, please refer to the [relevant issue](https://github.com/enoche/BM3/issues/9#issuecomment-1843973175) in our another repository.
Thank you for your reply, but I still don't understand. Is the file obtained by using CNN/VIT to extract the features of the self-built Data set consistent with the file organization form provided by Amazon Product Data? Can I continue to use the code of the.npy file obtained by you for the extracted image features in preprocessing

**Comment by enoche** [comment]
> Is the file obtained by using CNN/VIT to extract the features of the self-built Data set consistent with the file organization form provided by Amazon Product Data? 

Yes.

> Can I continue to use the code of the.npy file obtained by you for the extracted image features in preprocessing.

Sure, a few works already built on these features.

Thanks.
