### ISSUE TITLE
Request to Add "MicroLens" Dataset to MMRec Framework

### ISSUE THREAD

**Issue by yxni98** [enoche/MMRec#29]
Hi @enoche , thanks for your great contributions to the recommender system community !

I noticed that MMRec currently includes three datasets (Baby, Sports, Elec) in prepared formats. Could you add a newly multi-modal short-video dataset "MicroLens" to further promote the research?

I have already processed the dataset files (u_id_mapping.csv, i_id_mapping.csv, i_id_mapping.tsv, image_feat.npy, text_feat.npy, microlens.inter) to fit your framework. You can find them in this Google Drive link: https://drive.google.com/drive/folders/14UyTAh_YyDV8vzXteBJiy9jv8TBDK43w?usp=drive_link.

Thanks for your support !

**Comment by enoche** [comment]
Thanks @yxni98 for contributing the multimodal dataset! I've added it to the data directory [here](https://github.com/enoche/MMRec/blob/master/data/README.md). To enhance dataset usage, please consider adding a *.config file for this dataset.

**Comment by yxni98** [comment]
Hi @enoche , I have made a pull request to upload the yaml file for your convenience.

**Comment by enoche** [comment]
> Hi @enoche , I have made a pull request to upload the yaml file for your convenience.

Thanks a lot for your contribution~    Merged!!!

**Comment by MeycL** [comment]
Could I ask everyone if the feature extraction for this new dataset (especially for image and text) is consistent with the methods used in MMRec?
