### ISSUE TITLE
如何处理的图片数据

### ISSUE THREAD

**Issue by Marsffish** [enoche/MMRec#33]
请问这三个数据集的图片是使用什么哪一个预训练模型处理的，我想自己制作一个数据集应该如何处理图片呢

**Comment by enoche** [comment]
Hi, Marsffish. 谢谢对本项目感兴趣。
由于数据集中原本 已经提供了 图片提供好的feature，这边是直接用。原数据中应该是用CNN。

如果您想用其它模型自己提取，可以参考这边：[https://github.com/enoche/BM3/issues/9](https://github.com/enoche/BM3/issues/9)

**Comment by Marsffish** [comment]
非常感谢您的回答！
