### ISSUE TITLE
Using categorical features for the rating field?

### ISSUE THREAD

**Issue by ptkenny** [enoche/MMRec#36]
Hi, I'm trying to understand how I could use this framework for recommending text content. It seems that in all the sample datasets that ratings are numerical, could I pass in a vector instead? My goal is to pass one-hot encoded vectors describing different kinds of interactions with content(i.e likes, shares, viewed entirely, etc) and get recommendations based on those and the content. Is this currently possible in MMRec?

Thanks!

**Comment by enoche** [comment]
Hi, @ptkenny Thanks for your interests on this Repo.
MMRec can be fed with one-hot vectors, and vectors pre-trained on the Content (image, text etc.), but not raw content directly.
