### ISSUE TITLE
dragon

### ISSUE THREAD

**Issue by yongyuandishen2021** [enoche/MMRec#37]
why i can't find user_graph_dict.npy?how to generate it?

**Comment by enoche** [comment]
Hi, @yongyuandishen2021 you can refer the `preprocessing` pipeline here: https://github.com/enoche/MMRec/tree/master/preprocessing

**Comment by yongyuandishen2021** [comment]
> Hi, @yongyuandishen2021 you can refer the `preprocessing` pipeline here: https://github.com/enoche/MMRec/tree/master/preprocessing

I got it. Thank you very much,wish you success in your research
