### ISSUE TITLE
About the result of MVGAE

### ISSUE THREAD

**Issue by THU-Yu-Shang** [enoche/MMRec#4]
Hi, recently I'm running MVGAE using the framework but got very low results, for example on the baby dataset, the recall is nearly zero, my settings are: learning rate=0.001, beta=1, reg_weight=0.001, epochs=200. Have you got the right results of MVGAE using the framework? Thank you!

**Comment by enoche** [comment]
Thanks for your report. I am also confused with the results. You may check: https://github.com/enoche/MultimodalRecSys

Honestly, I've contacted the authors, but without response.  I would encourage you contact the authors personally. 
If you can reproduce their results, please help to update the model. Thanks.
