### ISSUE TITLE
Why even the example is not good

### ISSUE THREAD

**Issue by Guanyu-Lin** [enoche/MMRec#44]
Traceback (most recent call last):
  File "main.py", line 27, in <module>
    quick_start(model=args.model, dataset=args.dataset, config_dict=config_dict, save_model=True, mg=args.mg)
AttributeError: 'Namespace' object has no attribute 'mg'

**Comment by enoche** [comment]
Thanks for your feedback. You may update the code in `main.py` as:
`quick_start(model=args.model, dataset=args.dataset, config_dict=config_dict, save_model=True)` if you are not using MG model.

**Comment by jiwoo0212** [comment]
> Thanks for your feedback. You may update the code in `main.py` as: `quick_start(model=args.model, dataset=args.dataset, config_dict=config_dict, save_model=True)` if you are not using MG model.

I have the same issue. What is the MG model?

**Comment by rkl71** [comment]
> I have the same issue. What is the MG model? And is there a example code for execution?

I think the MG model is Mirror Gradient. When this model is added, the result will be better.
[Paper](https://dl.acm.org/doi/pdf/10.1145/3589334.3645553)  [Code](https://github.com/Qrange-group/Mirror-Gradient)

I didn't find the MG model in this code, but included other good models. Maybe you can try it.
