### ISSUE TITLE
What is to be used as textual modality input when extracting the textual feature (of Amazon dataset)?

### ISSUE THREAD

**Issue by WeixinChen98** [enoche/MMRec#6]
Hi, I am a bit confused about what to be used to extract the textual feature.

If as mentioned in your paper, the text description will be used:

> The metadata of the amazon datasets contains the text description and the URL of images that could be used as textual and visual modalities.

but if as mentioned in the code comments, the title, brand, category, and description will be used:
`# sentences: title + brand + category + description | All have title + description`

Could you please tell me which one I should refer to?

Thanks for your contributions to the community of multimodal recommendation!

**Comment by enoche** [comment]
Hi, @WeixinChen98, thanks for your kind feedback on this issue.
Great question!  Please follow the code.
In paper, we simply abstract the textual information associated with items as "text descriptions".

**Comment by WeixinChen98** [comment]
Thanks for your explanation!
