### ISSUE TITLE
About the implementation of saving and loading models

### ISSUE THREAD

**Issue by WeixinChen98** [enoche/MMRec#7]
Hi, I just found the "saved" variable in the function Trainer.fit is not yet used when I wanted to save and load the best model parameters for further research.

```
    def fit(self, train_data, valid_data=None, test_data=None, saved=False, verbose=True):
        r"""Train the model based on the train data and the valid data.

        Args:
            train_data (DataLoader): the train data
            valid_data (DataLoader, optional): the valid data, default: None.
                                               If it's None, the early_stopping is invalid.
            test_data (DataLoader, optional): None
            verbose (bool, optional): whether to write training and evaluation information to logger, default: True
            saved (bool, optional): whether to save the model parameters, default: True

        Returns:
             (float, dict): best valid score and best valid result. If valid_data is None, it returns (-1, None)
        """
```

Could you please update the code for the saving and loading functions of the best model parameters? That would be very helpful for my current research.

Thanks again for your great contributions!

**Comment by WeixinChen98** [comment]
Solved.

**Comment by enoche** [comment]
@WeixinChen98  Hi, WeixinChen98, thanks for your posting, you may refer here for model saving and loading. https://github.com/enoche/BM3/tree/master/trained-models-logs

**Comment by WeixinChen98** [comment]
> @WeixinChen98 Hi, WeixinChen98, thanks for your posting, you may refer here for model saving and loading. https://github.com/enoche/BM3/tree/master/trained-models-logs

Many thanks for your kind reply!
