### ISSUE TITLE
Product ID and userID for the Baby/Sports/Elec data

### ISSUE THREAD

**Issue by billy322** [enoche/MMRec#8]
Hi, can I get the orignal product iD and user ID in your preprocessed Baby/Sports/Elec dataset in this page:
https://github.com/enoche/MMRec/tree/master/data

thanks

**Comment by enoche** [comment]
Hi, @billy322 Sorry for my late response and thanks for your interest on this repo. 
Original ID mapping can be obtained in `https://github.com/enoche/MMRec/tree/master/preprocessing` stages.

For the IDs preprocessed by us, pls refer: https://drive.google.com/drive/folders/13cBy1EA_saTUuXxVllKgtfci2A09jyaG?usp=sharing
