### ISSUE TITLE
I have some confusion about regarding user interacted items as positive samples

### ISSUE THREAD

**Issue by XuHao-bit** [enoche/MMRec#9]
In the open-source datasets, such as the Baby dataset, I have observed that there are interaction records with very low ratings in the `baby.inter`  (e.g., `6 5374 1.0 1374019200 2` has a rating of 1). But I see that in the metric calculation part of the codes, the  user interacted items are considered positive samples and the items that have not interacted are considered negative samples. However, the current scenario will also consider some low-rated items as positive samples. Does this situation of treating low-rated items as positive samples introduce bias? Does it affect the model training process?

**Comment by enoche** [comment]
> Does this situation of treating low-rated items as positive samples introduce bias? Does it affect the model training process?
Both answers are yes.

Hi, @XuHao-bit Thanks for your feedback. In this repo, we follow previous research settings by treating all interactions as implicit feedback (0/1), all ratings are discretized into 0/1.
There are some other research papers that only keep ratings >= 3 or ==5 as positive samples. You may train the our models under different settings and analyze the results.
We are expecting your experimental reports. Thanks.
